/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import database.Koneksi;
import java.awt.Color;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author hafid
 */
public class CetakNoOrder extends javax.swing.JFrame {

    /**
     * Creates new form CetakNoOrder
     */
    public CetakNoOrder() {
        initComponents();
        
        btnCetak.setBackground(new Color(0,0,0,0));
        btnCetak.setOpaque(false);
        
        btnKembali.setBackground(new Color(0,0,0,0));
        btnKembali.setOpaque(false);
        
        getDataNama();
    }
    
    public void getDataNama() {
        try {              
            String sql = "SELECT * FROM orders ORDER BY ID_orders DESC LIMIT 1";
            Statement stat = Koneksi.GetConnection().createStatement();
            ResultSet res = stat.executeQuery(sql);
            if (res.next()) {
                tNoOrder.setText(res.getString("ID_orders"));
            } else {
                JOptionPane.showMessageDialog(rootPane, "Nomor Order Tidak Di Temukan");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Gagal Mengambil Data");
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCetak = new javax.swing.JPanel();
        btnKembali = new javax.swing.JPanel();
        tNoOrder = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 773));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(1100, 773));
        jPanel1.setLayout(null);

        btnCetak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCetakMouseClicked(evt);
            }
        });
        jPanel1.add(btnCetak);
        btnCetak.setBounds(450, 645, 200, 50);

        btnKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKembaliMouseClicked(evt);
            }
        });
        jPanel1.add(btnKembali);
        btnKembali.setBounds(10, 10, 60, 60);

        tNoOrder.setFont(new java.awt.Font("Segoe UI Semibold", 0, 135)); // NOI18N
        tNoOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tNoOrder.setText("1");
        tNoOrder.setAlignmentY(0.0F);
        tNoOrder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tNoOrder);
        tNoOrder.setBounds(420, 209, 260, 160);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Print Order Numbers.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1100, 773);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1100, 780);

        setSize(new java.awt.Dimension(1100, 773));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCetakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCetakMouseClicked
        // TODO add your handling code here:
        java.sql.Connection con = null;

        try {
            String jdbcDriver = "com.mysql.jdbc.Driver";
            Class.forName(jdbcDriver);

            String url = "jdbc:mysql://localhost:3306/toko_kue";
            String user = "root";
            String pass = "";

            con = DriverManager.getConnection(url, user, pass);
            
            try {
                String report = "C:\\Users\\hafid\\OneDrive\\Documents\\NetBeansProjects\\TOKO KUE\\src\\cetakNoOrder\\cetakNomor.jrxml";
                HashMap hash = new HashMap();
                hash.put("IdOrder", tNoOrder.getText());
                JasperReport JsRpt = JasperCompileManager.compileReport(report);
                JasperPrint jsPrint = JasperFillManager.fillReport(JsRpt, hash, con);
                JasperViewer.viewReport(jsPrint, false);
            } catch (Exception ex) {
                System.out.println(ex);
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }    
    }//GEN-LAST:event_btnCetakMouseClicked

    private void btnKembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKembaliMouseClicked
        // TODO add your handling code here:
        this.dispose();
        
        new DashboardOrder().setVisible(true);
    }//GEN-LAST:event_btnKembaliMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CetakNoOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CetakNoOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CetakNoOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CetakNoOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CetakNoOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCetak;
    private javax.swing.JPanel btnKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tNoOrder;
    // End of variables declaration//GEN-END:variables
}
