/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author hafid
 */
public class CustomCake extends javax.swing.JFrame {

    /**
     * Creates new form CustomCake
     */
    public CustomCake() {
        initComponents();
        
        btnTele.setBackground(new Color(0,0,0,0));
        btnTele.setOpaque(false);
        
        btnWA.setBackground(new Color(0,0,0,0));
        btnWA.setOpaque(false);
        
        btnIG.setBackground(new Color(0,0,0,0));
        btnIG.setOpaque(false);
        
        btnKembali.setBackground(new Color(0,0,0,0));
        btnKembali.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnKembali = new javax.swing.JPanel();
        btnWA = new javax.swing.JPanel();
        btnIG = new javax.swing.JPanel();
        btnTele = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 733));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(1100, 733));
        jPanel1.setLayout(null);

        btnKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKembaliMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnKembaliLayout = new javax.swing.GroupLayout(btnKembali);
        btnKembali.setLayout(btnKembaliLayout);
        btnKembaliLayout.setHorizontalGroup(
            btnKembaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );
        btnKembaliLayout.setVerticalGroup(
            btnKembaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        jPanel1.add(btnKembali);
        btnKembali.setBounds(10, 10, 55, 55);

        btnWA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnWAMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnWALayout = new javax.swing.GroupLayout(btnWA);
        btnWA.setLayout(btnWALayout);
        btnWALayout.setHorizontalGroup(
            btnWALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );
        btnWALayout.setVerticalGroup(
            btnWALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        jPanel1.add(btnWA);
        btnWA.setBounds(520, 610, 55, 55);

        btnIG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIGMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnIGLayout = new javax.swing.GroupLayout(btnIG);
        btnIG.setLayout(btnIGLayout);
        btnIGLayout.setHorizontalGroup(
            btnIGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );
        btnIGLayout.setVerticalGroup(
            btnIGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        jPanel1.add(btnIG);
        btnIG.setBounds(583, 610, 55, 55);

        btnTele.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTeleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnTeleLayout = new javax.swing.GroupLayout(btnTele);
        btnTele.setLayout(btnTeleLayout);
        btnTeleLayout.setHorizontalGroup(
            btnTeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );
        btnTeleLayout.setVerticalGroup(
            btnTeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        jPanel1.add(btnTele);
        btnTele.setBounds(458, 610, 55, 55);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Custom Cake Screen.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1100, 733);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1100, 733);

        setSize(new java.awt.Dimension(1100, 733));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKembaliMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnKembaliMouseClicked

    ImageIcon iconTele = new ImageIcon(getClass().getResource("/assets/Telegram.png"));
    ImageIcon iconWA = new ImageIcon(getClass().getResource("/assets/WhatsApp.png"));
    ImageIcon iconIG = new ImageIcon(getClass().getResource("/assets/Instagram.png"));
    
    private void btnTeleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTeleMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "No : +62 822-4491-2180", "NARAHUBUNG TELEGRAM", JOptionPane.INFORMATION_MESSAGE, iconTele);
    }//GEN-LAST:event_btnTeleMouseClicked

    private void btnWAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWAMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "No : +62 822-4491-2180", "NARAHUBUNG WhatsApp", JOptionPane.INFORMATION_MESSAGE, iconWA);
    }//GEN-LAST:event_btnWAMouseClicked

    private void btnIGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIGMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "IG : @lulea.id", "NARAHUBUNG INSTAGRAM", JOptionPane.INFORMATION_MESSAGE, iconIG);
    }//GEN-LAST:event_btnIGMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomCake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomCake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomCake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomCake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomCake().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnIG;
    private javax.swing.JPanel btnKembali;
    private javax.swing.JPanel btnTele;
    private javax.swing.JPanel btnWA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
