/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author hafid
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashbaord
     */
    public Dashboard() {
        initComponents();
        
        tnamaMenu.setText("Dashboard");
        tIdKaryawan.setVisible(false);
        
        mDashboard mD = new mDashboard();
        jDesktopPane1.add(mD);
        mD.setVisible(true);
        
        logout.setBackground(new Color(0,0,0,0));
        logout.setOpaque(false);
        
        mDashboard.setBackground(new Color(0,0,0,0));
        mDashboard.setOpaque(false);
        
        mDataAnggota.setBackground(new Color(0,0,0,0));
        mDataAnggota.setOpaque(false);
        
        mLaporan.setBackground(new Color(0,0,0,0));
        mLaporan.setOpaque(false);
        
        mPesanan.setBackground(new Color(0,0,0,0));
        mPesanan.setOpaque(false);
        
        mStokBahan.setBackground(new Color(0,0,0,0));
        mStokBahan.setOpaque(false);
        
        mTransaksi.setBackground(new Color(0,0,0,0));
        mTransaksi.setOpaque(false);
    }
    
    public void setData(JLabel data1, JLabel data2) {
        tnamaUser.setText(data1.getText());
        tIdKaryawan.setText(data2.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        mTransaksi = new javax.swing.JPanel();
        logout = new javax.swing.JPanel();
        mDashboard = new javax.swing.JPanel();
        mPesanan = new javax.swing.JPanel();
        mStokBahan = new javax.swing.JPanel();
        mLaporan = new javax.swing.JPanel();
        mDataAnggota = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tnamaMenu = new javax.swing.JLabel();
        tIdKaryawan = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tnamaUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(845, 690));
        jDesktopPane1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jDesktopPane1);
        jDesktopPane1.setBounds(256, 48, 845, 690);

        mTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mTransaksiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mTransaksiLayout = new javax.swing.GroupLayout(mTransaksi);
        mTransaksi.setLayout(mTransaksiLayout);
        mTransaksiLayout.setHorizontalGroup(
            mTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        mTransaksiLayout.setVerticalGroup(
            mTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(mTransaksi);
        mTransaksi.setBounds(10, 220, 220, 30);

        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout logoutLayout = new javax.swing.GroupLayout(logout);
        logout.setLayout(logoutLayout);
        logoutLayout.setHorizontalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        logoutLayout.setVerticalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(logout);
        logout.setBounds(1040, 10, 50, 30);

        mDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mDashboardMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mDashboardLayout = new javax.swing.GroupLayout(mDashboard);
        mDashboard.setLayout(mDashboardLayout);
        mDashboardLayout.setHorizontalGroup(
            mDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        mDashboardLayout.setVerticalGroup(
            mDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(mDashboard);
        mDashboard.setBounds(10, 180, 220, 30);

        mPesanan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mPesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mPesananMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mPesananLayout = new javax.swing.GroupLayout(mPesanan);
        mPesanan.setLayout(mPesananLayout);
        mPesananLayout.setHorizontalGroup(
            mPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        mPesananLayout.setVerticalGroup(
            mPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(mPesanan);
        mPesanan.setBounds(10, 260, 220, 30);

        mStokBahan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mStokBahan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mStokBahanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mStokBahanLayout = new javax.swing.GroupLayout(mStokBahan);
        mStokBahan.setLayout(mStokBahanLayout);
        mStokBahanLayout.setHorizontalGroup(
            mStokBahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        mStokBahanLayout.setVerticalGroup(
            mStokBahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(mStokBahan);
        mStokBahan.setBounds(10, 300, 220, 30);

        mLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mLaporanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mLaporanLayout = new javax.swing.GroupLayout(mLaporan);
        mLaporan.setLayout(mLaporanLayout);
        mLaporanLayout.setHorizontalGroup(
            mLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        mLaporanLayout.setVerticalGroup(
            mLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(mLaporan);
        mLaporan.setBounds(10, 340, 220, 30);

        mDataAnggota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mDataAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mDataAnggotaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mDataAnggotaLayout = new javax.swing.GroupLayout(mDataAnggota);
        mDataAnggota.setLayout(mDataAnggotaLayout);
        mDataAnggotaLayout.setHorizontalGroup(
            mDataAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        mDataAnggotaLayout.setVerticalGroup(
            mDataAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(mDataAnggota);
        mDataAnggota.setBounds(10, 410, 220, 30);

        jPanel2.setBackground(new java.awt.Color(75, 53, 36));

        tnamaMenu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tnamaMenu.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tnamaMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tnamaMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(305, 10, 120, 30);

        tIdKaryawan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tIdKaryawan.setForeground(new java.awt.Color(255, 255, 255));
        tIdKaryawan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tIdKaryawan);
        tIdKaryawan.setBounds(10, 50, 70, 30);

        jPanel3.setBackground(new java.awt.Color(103, 56, 21));

        tnamaUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tnamaUser.setForeground(new java.awt.Color(255, 255, 255));
        tnamaUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tnamaUser, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tnamaUser, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(78, 115, 100, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Dashboard.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1100, 733);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1101, 738);

        setSize(new java.awt.Dimension(1100, 733));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        int logout = JOptionPane.showConfirmDialog(rootPane, "Apakah Anda Ingin Menutup Aplikasi ?", "Tutup Aplikasi", JOptionPane.YES_NO_OPTION);
        if (logout == JOptionPane.YES_OPTION) {
//            Login_Screen lg = new Login_Screen();
//            lg.setVisible(true);
//            this.dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_logoutMouseClicked

    private void mDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mDashboardMouseClicked
        // TODO add your handling code here:
        tnamaMenu.setText("Dashboard");
        
        mDashboard mD = new mDashboard();
        jDesktopPane1.add(mD);
        mD.setVisible(true);
    }//GEN-LAST:event_mDashboardMouseClicked

    private void mTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mTransaksiMouseClicked
        // TODO add your handling code here:
        tnamaMenu.setText("Transaksi");
        
        mTransaksi mT = new mTransaksi();
        jDesktopPane1.add(mT);
        mT.setVisible(true);
        mT.setData(tIdKaryawan);
    }//GEN-LAST:event_mTransaksiMouseClicked

    private void mPesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mPesananMouseClicked
        // TODO add your handling code here:
        tnamaMenu.setText("Pesanan");
        
        mDetailPesanan mDPsn = new mDetailPesanan(jDesktopPane1);
        jDesktopPane1.add(mDPsn);
        mDPsn.setVisible(true);
    }//GEN-LAST:event_mPesananMouseClicked

    private void mStokBahanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mStokBahanMouseClicked
        // TODO add your handling code here:
        tnamaMenu.setText("Stok Bahan");
        
        mMasterStok mstStok = new mMasterStok();
        jDesktopPane1.add(mstStok);
        mstStok.setVisible(true);
        mstStok.setData(tIdKaryawan);
    }//GEN-LAST:event_mStokBahanMouseClicked

    private void mLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mLaporanMouseClicked
        // TODO add your handling code here:
        tnamaMenu.setText("Laporan");
        
        mLaporan mLprn = new mLaporan();
        jDesktopPane1.add(mLprn);
        mLprn.setVisible(true);
    }//GEN-LAST:event_mLaporanMouseClicked

    private void mDataAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mDataAnggotaMouseClicked
        // TODO add your handling code here:
        tnamaMenu.setText("Data Anggota");
        
        mMasterPengguna mstPgn = new mMasterPengguna();
        jDesktopPane1.add(mstPgn);
        mstPgn.setVisible(true);
    }//GEN-LAST:event_mDataAnggotaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel mDashboard;
    private javax.swing.JPanel mDataAnggota;
    private javax.swing.JPanel mLaporan;
    private javax.swing.JPanel mPesanan;
    private javax.swing.JPanel mStokBahan;
    private javax.swing.JPanel mTransaksi;
    private javax.swing.JLabel tIdKaryawan;
    private javax.swing.JLabel tnamaMenu;
    private javax.swing.JLabel tnamaUser;
    // End of variables declaration//GEN-END:variables
}
