/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import database.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import popMessage.PopUpForget;
import popMessage.PopUpForgetErr;

/**
 *
 * @author hafid
 */
public class Forget_Password extends javax.swing.JFrame {

    /**
     * Creates new form Forget_Password
     */
    public Forget_Password() {
        initComponents();
    }
    
    public void bersih() {
        username.setText("");
        hobi.setText("");
        passBaru.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        hobi = new javax.swing.JTextField();
        passBaru = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        tLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        btnUpdate.setBackground(new java.awt.Color(145, 109, 83));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate);
        btnUpdate.setBounds(810, 550, 170, 50);

        hobi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        hobi.setBorder(null);
        jPanel1.add(hobi);
        hobi.setBounds(750, 300, 330, 50);

        passBaru.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        passBaru.setBorder(null);
        jPanel1.add(passBaru);
        passBaru.setBounds(750, 410, 330, 50);

        username.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        username.setBorder(null);
        jPanel1.add(username);
        username.setBounds(750, 190, 330, 40);

        jPanel2.setBackground(new java.awt.Color(163, 135, 114));

        tLogin.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tLogin.setForeground(new java.awt.Color(255, 255, 255));
        tLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tLogin.setText("Login ?");
        tLogin.setToolTipText("");
        tLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(tLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(800, 490, 190, 40);

        jLabel1.setBackground(new java.awt.Color(145, 109, 83));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Lupa Password.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1200, 650);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1200, 1250);

        setSize(new java.awt.Dimension(1200, 650));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
            if (username.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Mohon Masukan Email Anda!");
                username.requestFocus();
            } else if (hobi.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Mohon Masukan Hobi Anda!");
                hobi.requestFocus();
            } else if (passBaru.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Mohon Masukan Pasukan Baru Anda!");
                passBaru.requestFocus();
            } else {
                  String sql = "SELECT * FROM pegawai WHERE email_pegawai='"+ username.getText() +"' "
                             + "AND hobi = '"+ hobi.getText() +"'";
                  PreparedStatement stat = Koneksi.GetConnection().prepareStatement(sql);
                  ResultSet res = stat.executeQuery();
                  if (res.next()) {
                        if (!hobi.getText().equals(res.getString("hobi"))) {
                            JOptionPane.showMessageDialog(rootPane, "Hobi Yang Anda Masukan Salah!");
                        } else if (passBaru.getText().equals(res.getString("password_pegawai"))) {
                            int selectOption = JOptionPane.showConfirmDialog(rootPane, "Password Sama, Apakah Anda Yakin Tetap Merubah Password ?", "Password Baru Sama!", JOptionPane.YES_NO_OPTION);
                    
                            if (selectOption == JOptionPane.YES_OPTION){
                              String sqll = "UPDATE pegawai SET password_pegawai='"+ passBaru.getText() +"' WHERE email_pegawai='"+ res.getString("ID_pegawai") +"'";
                              PreparedStatement stats = Koneksi.GetConnection().prepareStatement(sqll);
                              stats.executeUpdate();
                              bersih();
                              PopUpForget pug = new PopUpForget();
                              pug.setVisible(true);
                            }
                        } else {
                            String sqll = "UPDATE pegawai SET password_pegawai='"+ passBaru.getText() +"' WHERE ID_pegawai='"+ res.getString("ID_pegawai") +"'";
                            PreparedStatement stats = Koneksi.GetConnection().prepareStatement(sqll);
                            stats.executeUpdate();
                            bersih();
                            PopUpForget pug = new PopUpForget();
                            pug.setVisible(true);
                        }
                  };
            }
        } catch (Exception ex) {
            PopUpForgetErr pugr = new PopUpForgetErr();
            pugr.setVisible(true);
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tLoginMouseClicked
        // TODO add your handling code here:
        Login_Screen lc = new Login_Screen();
        this.dispose();
        lc.setVisible(true);
    }//GEN-LAST:event_tLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forget_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forget_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forget_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forget_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forget_Password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField hobi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField passBaru;
    private javax.swing.JLabel tLogin;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
