/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.glass.events.KeyEvent;
import database.Koneksi;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author hafid
 */
public class mMasterStok extends javax.swing.JInternalFrame {

    /**
     * Creates new form mMasterStok
     */
    private int hargaSatuan = 0;
    NumberFormat nf = NumberFormat.getNumberInstance(new Locale("in", "ID"));
    
    public mMasterStok() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        
        tGetIdPegawai.setVisible(false);
        
        dataTanggal.setVisible(false);
        tIdBarang.setVisible(false);
        
        btnSimpan.setBackground(new Color(0,0,0,0));
        btnSimpan.setOpaque(false);
        
        btnEdit.setBackground(new Color(0,0,0,0));
        btnEdit.setOpaque(false);
        
        btnHapus.setBackground(new Color(0,0,0,0));
        btnHapus.setOpaque(false);
        
        dataTabel();
    }

    public void dataTabel() {        
        DefaultTableModel tbl = new DefaultTableModel(){
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        
        tbl.addColumn("ID Barang");
        tbl.addColumn("Nama Barang");
        tbl.addColumn("Stok Barang (Kg)");
        tbl.addColumn("Tanggal Exp");
        tbl.addColumn("Harga Satuan (Rp)");
        tabel.setModel(tbl);

        try {
            String sql = "SELECT ID_barang, nama_barang, stok_barang, "
                         + "DATE_FORMAT(tanggal_exp, '%d-%m-%Y') AS tanggal, harga_satuan  FROM barang";
            Statement stat = Koneksi.GetConnection().createStatement();
            ResultSet res = stat.executeQuery(sql);
            while(res.next()) {
                tbl.addRow(new Object[]{
                    res.getString("ID_barang"),
                    res.getString("nama_barang"),
                    res.getString("stok_barang"),
                    res.getString("tanggal"),
                    nf.format(Integer.parseInt(res.getString("harga_satuan"))),
                });
                tabel.setModel(tbl);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Data Gagal Diambil");
            System.out.println(ex);
        }
    }
    
    public void bersih() {
        tNama.setText("");
        tStok.setText("");
        tKalender.setDate(null);
        tHargaSatuan.setText("");
        tCari.setText("");
    }
    
    public void setData(JLabel data) {
        tGetIdPegawai.setText(data.getText());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tStok = new javax.swing.JTextField();
        tHargaSatuan = new javax.swing.JTextField();
        tNama = new javax.swing.JTextField();
        tIdBarang = new javax.swing.JLabel();
        tKalender = new com.toedter.calendar.JDateChooser();
        btnHapus = new javax.swing.JPanel();
        btnEdit = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        tCari = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dataTanggal = new javax.swing.JLabel();
        tGetIdPegawai = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(845, 690));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(845, 690));
        jPanel1.setPreferredSize(new java.awt.Dimension(845, 690));
        jPanel1.setLayout(null);

        tStok.setBackground(new java.awt.Color(248, 248, 245));
        tStok.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tStok.setBorder(null);
        tStok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tStokKeyTyped(evt);
            }
        });
        jPanel1.add(tStok);
        tStok.setBounds(190, 153, 120, 30);

        tHargaSatuan.setBackground(new java.awt.Color(248, 248, 245));
        tHargaSatuan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tHargaSatuan.setBorder(null);
        tHargaSatuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tHargaSatuanKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tHargaSatuanKeyTyped(evt);
            }
        });
        jPanel1.add(tHargaSatuan);
        tHargaSatuan.setBounds(190, 240, 180, 30);

        tNama.setBackground(new java.awt.Color(248, 248, 245));
        tNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tNama.setBorder(null);
        jPanel1.add(tNama);
        tNama.setBounds(190, 111, 200, 30);
        jPanel1.add(tIdBarang);
        tIdBarang.setBounds(430, 110, 70, 30);
        jPanel1.add(tKalender);
        tKalender.setBounds(185, 197, 195, 30);

        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnHapusLayout = new javax.swing.GroupLayout(btnHapus);
        btnHapus.setLayout(btnHapusLayout);
        btnHapusLayout.setHorizontalGroup(
            btnHapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        btnHapusLayout.setVerticalGroup(
            btnHapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(btnHapus);
        btnHapus.setBounds(417, 299, 100, 30);

        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnEditLayout = new javax.swing.GroupLayout(btnEdit);
        btnEdit.setLayout(btnEditLayout);
        btnEditLayout.setHorizontalGroup(
            btnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );
        btnEditLayout.setVerticalGroup(
            btnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(btnEdit);
        btnEdit.setBounds(309, 301, 85, 30);

        btnSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnSimpanLayout = new javax.swing.GroupLayout(btnSimpan);
        btnSimpan.setLayout(btnSimpanLayout);
        btnSimpanLayout.setHorizontalGroup(
            btnSimpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        btnSimpanLayout.setVerticalGroup(
            btnSimpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(btnSimpan);
        btnSimpan.setBounds(187, 301, 100, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Form Stok Master.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(71, 53, 450, 280);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(71, 449, 690, 175);

        tCari.setBackground(new java.awt.Color(248, 248, 245));
        tCari.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tCariKeyReleased(evt);
            }
        });
        jPanel1.add(tCari);
        tCari.setBounds(593, 400, 170, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Cari :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(550, 400, 31, 30);
        jPanel1.add(dataTanggal);
        dataTanggal.setBounds(580, 90, 0, 0);

        tGetIdPegawai.setText("jLabel1");
        jPanel1.add(tGetIdPegawai);
        tGetIdPegawai.setBounds(560, 90, 100, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 845, 690);

        setBounds(0, 0, 845, 690);
    }// </editor-fold>//GEN-END:initComponents
     
    private void tCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCariKeyReleased
        // TODO add your handling code here:
        DefaultTableModel tbl = new DefaultTableModel(){
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        
        tbl.addColumn("ID Barang");
        tbl.addColumn("Nama Barang");
        tbl.addColumn("Stok Barang (Kg)");
        tbl.addColumn("Tanggal Exp");
        tbl.addColumn("Harga Satuan (Rp)");
        tabel.setModel(tbl);

        try {
             String sql = "SELECT ID_barang, nama_barang, stok_barang, "
                          + "DATE_FORMAT(tanggal_exp, '%d-%m-%Y') AS tanggal, harga_satuan "
                          + "FROM barang WHERE ID_barang LIKE '%"+ tCari.getText() +"%' ORDER BY barang.ID_barang ASC";
            Statement stat = Koneksi.GetConnection().createStatement();
            ResultSet res = stat.executeQuery(sql);
            while(res.next()) {
                tbl.addRow(new Object[]{
                    res.getString("ID_barang"),
                    res.getString("nama_barang"),
                    res.getString("stok_barang"),
                    res.getString("tanggal"),
                     nf.format(Integer.parseInt(res.getString("harga_satuan"))),
                });
                tabel.setModel(tbl);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Data Gagal Diambil");
            System.out.println(ex);
        }
    }//GEN-LAST:event_tCariKeyReleased

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        // TODO add your handling code here:        
        String tanggal1 = String.valueOf(tKalender.getDate());
        dataTanggal.setText(tanggal1);
        
        String hrgStn = tHargaSatuan.getText();
        int hrgSatuan = hrgStn.isEmpty() ? 0 : Integer.parseInt(hrgStn);
        this.hargaSatuan = hrgSatuan;
        
        if (tNama.getText().isEmpty() || tStok.getText().isEmpty() || 
            dataTanggal.getText().equals("null") || tHargaSatuan.getText().isEmpty() || tGetIdPegawai.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Mohon Isi Seluruh Form Data Barang!");
        } else {
            try {
                String tampilan = "yyyy-MM-dd";
                SimpleDateFormat fm = new SimpleDateFormat(tampilan);
                String tanggal = String.valueOf(fm.format(tKalender.getDate()));
                
                String sql = "INSERT INTO barang (nama_barang, stok_barang, tanggal_exp, harga_satuan, ID_pegawai) "
                             + "VALUES ('"+ tNama.getText() +"', '"+ tStok.getText() +"', "
                             + "'"+ tanggal +"', '"+ hargaSatuan +"', '"+ tGetIdPegawai.getText() +"')";
                Statement stat = Koneksi.GetConnection().createStatement();
                stat.execute(sql);
                JOptionPane.showMessageDialog(rootPane, "Data Barang Berhasil Di Tambahkan!");
                bersih();
                dataTabel();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, "Data Barang Gagal Di Tambahkan!");
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void tStokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tStokKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_tStokKeyTyped

    private void tHargaSatuanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tHargaSatuanKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_tHargaSatuanKeyTyped

    private void tHargaSatuanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tHargaSatuanKeyReleased
        // TODO add your handling code here:
//        String S_angka_normal = tHargaSatuan.getText().replaceAll("\\,", "");
//        double D_angka_Normal = Double.parseDouble(S_angka_normal);
//        DecimalFormat DF = new DecimalFormat("#,###,###");        
//        tHargaSatuan.setText(DF.format(D_angka_Normal));
    }//GEN-LAST:event_tHargaSatuanKeyReleased

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        // TODO add your handling code here:
        String tanggal1 = String.valueOf(tKalender.getDate());
        dataTanggal.setText(tanggal1);
        
        String hrgStn = tHargaSatuan.getText();
        int hrgSatuan = hrgStn.isEmpty() ? 0 : Integer.parseInt(hrgStn);
        this.hargaSatuan = hrgSatuan;
        
        if (tNama.getText().isEmpty() || tStok.getText().isEmpty() || 
            dataTanggal.getText().equals("null") || tHargaSatuan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Mohon Isi Seluruh Form Data Barang!");
        } else {
            try {
                String tampilan = "YYYY-MM-dd";
                SimpleDateFormat fm = new SimpleDateFormat(tampilan);
                String tanggal = String.valueOf(fm.format(tKalender.getDate()));
                
                String sql = "UPDATE barang SET nama_barang = '"+ tNama.getText() +"', "
                             + "stok_barang = '"+ tStok.getText() +"', tanggal_exp = '"+ tanggal +"',"
                             + "harga_satuan = '"+ hargaSatuan +"', ID_pegawai = '"+ tGetIdPegawai.getText() +"'"
                             + "WHERE ID_barang = '"+ tIdBarang.getText() +"'";
                Statement stat = Koneksi.GetConnection().createStatement();
                stat.execute(sql);
                JOptionPane.showMessageDialog(rootPane, "Data Barang Berhasil Di Ubah!");
                bersih();
                dataTabel();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, "Data Barang Gagal Di Ubah!");
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_btnEditMouseClicked

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
        // TODO add your handling code here:        
         if (tIdBarang.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Mohon Pilih Data Barang!");
        } else {
            int check = JOptionPane.showConfirmDialog(rootPane, "Apakah Anda Yakin Menghapus Data Ini ?", "Hapus Data", JOptionPane.YES_NO_OPTION);
            if (check == JOptionPane.YES_OPTION) {
                try {
                    String tampilan = "YYYY-MM-dd";
                    SimpleDateFormat fm = new SimpleDateFormat(tampilan);
                    String tanggal = String.valueOf(fm.format(tKalender.getDate()));

                    String sql = "DELETE FROM barang WHERE ID_barang = '"+ tIdBarang.getText() +"'";
                    Statement stat = Koneksi.GetConnection().createStatement();
                    stat.execute(sql);
                    JOptionPane.showMessageDialog(rootPane, "Data Barang Berhasil Di Hapus!");
                    bersih();
                    dataTabel();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(rootPane, "Data Barang Gagal Di Hapus!");
                    System.out.println(ex);
                }
            }
        }        
    }//GEN-LAST:event_btnHapusMouseClicked

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        int i = tabel.getSelectedRow();
        TableModel tb = tabel.getModel();
        
        try {
            Date tanggal = new SimpleDateFormat("d-M-y").parse((String)tb.getValueAt(i, 3).toString());
            tKalender.setDate(tanggal);
        } catch (ParseException ex) {
            Logger.getLogger(mMasterStok.class.getName()).log(Level.SEVERE, null, ex);
        }

        String data1 = tb.getValueAt(i, 0).toString();
        String data2 = tb.getValueAt(i, 1).toString();
        String data3 = tb.getValueAt(i, 2).toString();
        String data5 = tb.getValueAt(i, 4).toString();

        String data = tb.getValueAt(i, 4).toString();
        data = data.replace(".", "");
        
        tIdBarang.setText(data1);
        tNama.setText(data2);
        tStok.setText(data3);
        tHargaSatuan.setText(data);
        
    }//GEN-LAST:event_tabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnEdit;
    private javax.swing.JPanel btnHapus;
    private javax.swing.JPanel btnSimpan;
    private javax.swing.JLabel dataTanggal;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tCari;
    private javax.swing.JLabel tGetIdPegawai;
    private javax.swing.JTextField tHargaSatuan;
    private javax.swing.JLabel tIdBarang;
    private com.toedter.calendar.JDateChooser tKalender;
    private javax.swing.JTextField tNama;
    private javax.swing.JTextField tStok;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
